saisX/enrollment/urls.py
from . import views
from django.conf.urls import url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'home$', views.HomeView.as_view(), name='home'),
    url(r'login$', views.LoginView.as_view(), name="login"),
    url(r'profile$', views.ProfileView.as_view(), name='profile'),
    url(r'grades$', views.GradesView.as_view(), name='grades'),
    url(r'schedule$', views.ScheduleView.as_view(), name='schedule'),
    url(r'manage', views.ManageView.as_view(), name='manage'),
    url(r'edit$', views.EditView.as_view(), name='edit'),
    url(r'enroll$', views.EnrollView.as_view(), name='enroll'),
    url(r'enlist$', views.EnlistView.as_view(), name='enlist'),
    url(r'courses$', views.CoursesView.as_view(), name='courses'),
]

saisX/saisX/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('enrollment.urls', namespace='enrollment')),
]

saisX/enrollment/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.OneToOneField(User, related_name='student')
    student_number = models.CharField(max_length=9, primary_key=True)
    sais_number = models.CharField(max_length=8, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20)
    email = models.EmailField()
    contact_number = models.CharField(max_length=20)
    current_address = models.OneToOneField('Address', related_name='+')
    home_address = models.OneToOneField('Address', related_name='+')
    birthday = models.DateField()
    program = models.ForeignKey('Program', related_name='students')
    mother_name = models.CharField(max_length=50)
    mother_contact = models.CharField(max_length=20)
    father_name = models.CharField(max_length=50)
    father_contact = models.CharField(max_length=20)
    year_begin = models.DateField()
    institution = models.ForeignKey('Institution', related_name='students')


class Program(models.Model):
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=20)


class Address(models.Model):
    street = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10)


class Course(models.Model):
    CATEGORY_CHOICES = (
        ('MST', 'Math, Science, and Technology'),
        ('SSP', 'Social Sciences and '),
        ('AH', 'Arts and Humanities'),
    )
    name = models.CharField(max_length=20)
    description = models.TextField()
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    schedule = models.CharField(max_length=20)
    instructor = models.ForeignKey(
        'Instructor', related_name='courses_handled')
    units = models.IntegerField(default='2')
    room = models.CharField(max_length=20)


class Instructor(models.Model):
    name = models.CharField(max_length=50)


class Institution(models.Model):
    name = models.CharField(max_length=50)

saisX/enrollment/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import Student
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(min_length=3, widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(UserLoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        user =  authenticate(username=username, password=password)
        print user
        if user:
            cleaned_data['user'] = user
        else:
            raise forms.ValidationError(
                'Username/Password is incorrect.'
            )
        return cleaned_data


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['contact_number', 'email', 'mother_contact', 'father_contact', 'current_address', 'home_address']

saisX/enrollment/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, FormView, ListView
from .models import Student
from .forms import UserLoginForm, StudentForm

class HomeView(TemplateView):
    model = Student
    template_name = 'enrollment/home.html'


class LoginView(FormView):
    template_name = "enrollment/login.html"
    form_class = UserLoginForm
    success_view_name = 'enrollment:home'

    def get(self, request, *args, **kwargs):
        return super(LoginView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.cleaned_data['user']
        login(self.request, user)

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        next = self.request.GET.get('next')
        if next:
            return next

        else:
            return reverse(self.success_view_name)


class ScheduleView(TemplateView):
    model = Student
    template_name = 'enrollment/schedule.html'


class GradesView(ListView):
    model = Student
    template_name = 'enrollment/viewgrades.html'


class EditView(TemplateView):
    model = Student
    template_name = 'enrollment/edit_info.html'


class ProfileView(TemplateView):
    model = Student
    template_name = 'enrollment/profile.html'

class ManageView(TemplateView):
    template_name = 'enrollment/manage.html'

class EnrollView(TemplateView):
    template_name = 'enrollment/enroll.html'

class EnlistView(TemplateView):
    template_name = 'enrollment/enlist.html'

class CoursesView(TemplateView):
    template_name = 'enrollment/courses.html'

saisX/enrollment/templates/enrollment/course_list.html
{% extends 'saisX/base.html' %}

saisX/enrollment/templates/enrollment/enlist.html
{% include 'saisX/base.html' %}
{% load staticfiles %}

{% block title %}
<title>SAIS | Enlist Courses</title>
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row center green darken-4 white-text head-container" >
    <h4>Enlist Courses</h4>
  </div>
  <div class="row info-container grey lighten-3">
    <div class="row center">
      <div class="input-field offset-l2 offset-m2 offset-s2  col l8 m8 s8 center">
        <input type="text" id="search_course" class="validate center">
        <label for="search_course"><i class="material-icons" style="vertical-align: bottom">search</i>Search Course</label>
      </div>
    </div>
    <div class="row center">
      <h5><b>Search Results</b></h5>
    </div>
    <div class="row">
      <div class="offset-l2 offset-m2 offset-s2 col l8 m8 s8">
        <ul class="collection">
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course1">CMSC 22 A - Object-Oriented Programming</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check1">
                  <label for="course_check1"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course2">Bio 1 F - Introduction to Biology</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check2">
                  <label for="course_check2"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course3">Socsci 2 H - Something about SOCSCI</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check3">
                  <label for="course_check3"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course4">Math 17 B - Elementary Algebra and Trigonometry</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check4">
                  <label for="course_check4"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course5">CMSC 11 B - Introduction to Computer Science</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check5">
                  <label for="course_check5"></label>
                </form>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="row center">
      <div class="col l6 m12 s12">
        <a class="waves-effect waves-light btn enlist-button" href="#"><h6><span>Enlist Courses</span></h6></a>
      </div>
      <div class="col l6 m12 s12">
        <a class="waves-effect waves-light btn enroll-button" href="{% url 'enrollment:enroll' %}"><h6><span>Proceed to Enrollment</span></h6></a>
      </div>
    </div>
    <div class="row center">
      <a class="modal-trigger" href="#view_enlist">View Enlisted Courses >></a>
    </div>
  </div>
  <div id="course1" class="modal">
    <div class="modal-content">
      <h4>CMSC 22 - A</h4>
      <h5>Introduction to Object-Oriented Programming</h5>
      <p>
        Schedule: MTh 9:00-10:30 <br>
        Classroom: AS 302 <br>
        Instructor: Prof. Don Pakson <br>
        Category: Computer Science
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course2" class="modal">
    <div class="modal-content">
      <h4>Bio 1 - F</h4>
      <h5>Introduction to Biology</h5>
      <p>
        Schedule: TF 1:00-2:30 <br>
        Classroom: Room 126 <br>
        Instructor: Mr. Angelo Reymundo <br>
        Category: MST
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course3" class="modal">
    <div class="modal-content">
      <h4>Socsci 2 - H</h4>
      <h5>Something about SOCSCI</h5>
      <p>
        Schedule: MTh 10:30-12:00 <br>
        Classroom: AS 246 <br>
        Instructor: Prof. Axel Tan <br>
        Category: Social Sciences
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course4" class="modal">
    <div class="modal-content">
      <h4>Math 17 - B</h4>
      <h5>Elementary Algebra and Trigonometry</h5>
      <p>
        Schedule: TF 9:00-10:30 <br>
        Classroom: AS 206 <br>
        Instructor: Prof. Andrew Bluzi <br>
        Category: Math
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course5" class="modal">
    <div class="modal-content">
      <h4>CMSC 11 - B</h4>
      <h5>Introduction to Computer Science</h5>
      <p>
        Schedule: MTh 2:30-4:00 <br>
        Classroom: AS 306 <br>
        Instructor: Prof. Ryan Rehigor <br>
        Category: Computer Science
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="view_enlist" class="modal">
    <div class="modal-content">
      <ul class="collection">
        <<li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course1">CMSC 22 A - Object-Oriented Programming</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course2">Bio 1 F - Introduction to Biology</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course3">Socsci 2 H - Something about SOCSCI</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course4">Math 17 B - Elementary Algebra and Trigonometry</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course5">CMSC 11 B - Introduction to Computer Science </a>
              </div>
            </div>
          </li>
      </ul>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Enlist</a>
    </div>
  </div>
  <div id="view_enrolled" class="modal">
    <div class="modal-content">
      <ul class="collection">
        <<li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course1">CMSC 22 A - Object-Oriented Programming</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course2">Bio 1 F - Introduction to Biology</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course3">Socsci 2 H - Something about SOCSCI</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course4">Math 17 B - Elementary Algebra and Trigonometry</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course5">CMSC 11 B - Introduction to Computer Science </a>
              </div>
            </div>
          </li>
      </ul>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
</div>
{% endblock content %}

saisX/enrollment/templates/enrollment/enroll.html
{% include 'saisX/base.html' %}
{% load staticfiles %}

{% block title %}
<title>SAIS | Enrollment</title>
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row center green darken-4 white-text head-container" >
    <h4>Enroll Courses</h4>
  </div>
  <div class="row info-container grey lighten-3">
    <div class="row center">
      <h5><b>Enlisted Courses</b></h5>
    </div>
    <div class="row">
      <div class="offset-l2 offset-m2 offset-s2 col l8 m8 s8">
        <ul class="collection">
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course1">CMSC 22 A - Object-Oriented Programming</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check1">
                  <label for="course_check1"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course2">Bio 1 F - Introduction to Biology</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check2">
                  <label for="course_check2"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course3">Socsci 2 H - Something about SOCSCI</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check3">
                  <label for="course_check3"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course4">Math 17 B - Elementary Algebra and Trigonometry</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check4">
                  <label for="course_check4"></label>
                </form>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 0px">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course5">CMSC 11 B - Introduction to Computer Science</a>
              </div>
              <div class="col l1 m1 s1">
                <form action="#!">
                  <input type="checkbox" id="course_check5">
                  <label for="course_check5"></label>
                </form>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
      <div class="row center">
        <a class="waves-effect waves-light btn enroll-button" href="{% url 'enrollment:enroll' %}"><h6><span>Enroll Courses</span></h6></a>
      </div>
  </div>
  <div id="course1" class="modal">
    <div class="modal-content">
      <h4>CMSC 22 - A</h4>
      <h5>Introduction to Object-Oriented Programming</h5>
      <p>
        Schedule: MTh 9:00-10:30 <br>
        Classroom: AS 302 <br>
        Instructor: Prof. Don Pakson <br>
        Category: Computer Science
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course2" class="modal">
    <div class="modal-content">
      <h4>Bio 1 - F</h4>
      <h5>Introduction to Biology</h5>
      <p>
        Schedule: TF 1:00-2:30 <br>
        Classroom: Room 126 <br>
        Instructor: Mr. Angelo Reymundo <br>
        Category: MST
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course3" class="modal">
    <div class="modal-content">
      <h4>Socsci 2 - H</h4>
      <h5>Something about SOCSCI</h5>
      <p>
        Schedule: MTh 10:30-12:00 <br>
        Classroom: AS 246 <br>
        Instructor: Prof. Axel Tan <br>
        Category: Social Sciences
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course4" class="modal">
    <div class="modal-content">
      <h4>Math 17 - B</h4>
      <h5>Elementary Algebra and Trigonometry</h5>
      <p>
        Schedule: TF 9:00-10:30 <br>
        Classroom: AS 206 <br>
        Instructor: Prof. Andrew Bluzi <br>
        Category: Math
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="course5" class="modal">
    <div class="modal-content">
      <h4>CMSC 11 - B</h4>
      <h5>Introduction to Computer Science</h5>
      <p>
        Schedule: MTh 2:30-4:00 <br>
        Classroom: AS 306 <br>
        Instructor: Prof. Ryan Rehigor <br>
        Category: Computer Science
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OKAY!</a>
    </div>
  </div>
  <div id="view_enlist" class="modal">
    <div class="modal-content">
      <ul class="collection">
        <<li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course1">CMSC 22 A - Object-Oriented Programming</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course2">Bio 1 F - Introduction to Biology</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course3">Socsci 2 H - Something about SOCSCI</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course4">Math 17 B - Elementary Algebra and Trigonometry</a>
              </div>
            </div>
          </li>
          <li class="collection-item">
            <div class="row" style="margin-bottom: 3px !important">
              <div class="col l11 m11 s11">
                <a class="modal-trigger" href="#course5">CMSC 11 B - Introduction to Computer Science </a>
              </div>
            </div>
          </li>
      </ul>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Enlist</a>
    </div>
  </div>
</div>
{% endblock content %}

saisX/enrollment/templates/enrollment/home.html
{% extends 'saisX/base.html' %}
{% load staticfiles %}
{% block title %}
<title>SAIS | Home</title>
{% endblock title %}
{% block content %}
<div class="container">
  <div class="row center">
	  <h4 class="col l12 m12 s12">Welcome, {{ request.user.get_full_name }}</h4>
  </div>
  <div class="row">
    <div class="col l6 m12 s12 center hb-div">
      <a class="waves-effect waves-light btn home-buttons" href="{% url "enrollment:manage" %}"><h5><span >MANAGE MY COURSES</span></h5></a>
    </div>
    <div class="col l6 m12 s12 center hb-div">
		<a class="waves-effect waves-light btn home-buttons" href="{% url "enrollment:grades" %}"><h5><span >VIEW GRADES</span></h5></a>
    </div>
    <div class="col l6 m12 s12 center hb-div">
		<a class="waves-effect waves-light btn home-buttons" href="{% url "enrollment:schedule" %}"><h5><span>VIEW SCHEDULE</span></h5></a>
    </div>
    <div class="col l6 m12 s12 center hb-div">
      <a class="waves-effect waves-light btn home-buttons" href="{% url "enrollment:profile" %}"><h5><span>VIEW INFORMATION</span></h5></a>
    </div>
    <div class="col l6 m12 s12 center hb-div">
      <a class="waves-effect waves-light btn home-buttons" href="#"><h5><span>DOWNLOAD SYLLABUS</span></h5></a>
    </div>
  </div>
</div>
{% endblock content %}

saisX/enrollment/templates/enrollment/manage.html
{% include 'saisX/base.html' %}
{% load staticfiles %}

{% block title %}
<title>SAIS | Manage Courses</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row center green darken-4 white-text head-container" >
        <h4>Manage my Courses</h4>
    </div>
    <div class="row center info-container grey lighten-3" style="margin-top: 20px">
        <div class="col l12 m12 s12 center hb-div">
            <a class="waves-effect waves-light btn manage-buttons" href="{% url "enrollment:courses" %}"><h5><span >My Courses</span></h5></a>
        </div>
        <div class="col l12 m12 s12 center hb-div">
            <a class="waves-effect waves-light btn manage-buttons" href="{% url "enrollment:enlist" %}"><h5><span >Enlist</span></h5></a>
        </div>
    </div>
</div>
{% endblock content %}

saisX/enrollment/templates/enrollment/partials/course_item.html
{% extends 'saisX/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
  <div class="row center 9 green">
    
  </div>
</div>
{% endblock content %}

saisX/saisX/templates/saisX/base.html
{% load staticfiles %}
<!Doctype html>
<html>
  <head>
    {% block title %}
    {% endblock title %}
    <link href="{% static 'saisX/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'saisX/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block css %}
    {% endblock css %}
  </head>
  <body>
    <nav class="row red darken-4">
      <div class="nav-wrapper">
        <a href="#" class="brand-logo left" style = "height: 100% ; width: 64px"><img src="{% static 'saisX/img/logo.png' %}" alt="" width = "95%" height = "95%"/></a>
    		<div class="center title-l">
    			<h4>Student Academic Information System</h4>
    		</div>
    		<div class="center title-s">
    			<h4>SAIS</h4>
    		</div>
  	  </div>
    </nav>
    <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
      <a class="btn-floating btn-large red">
        <i class="material-icons">menu</i>
      </a>
      <ul>
        <li><a class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="View Grades" href="{% url "enrollment:grades" %}"><i class="material-icons">insert_chart</i></a></li>
        <li><a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="View Schedule" href="{% url "enrollment:schedule" %}"><i class="material-icons">toc</i></a></li>
        <li><a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Manage Courses" href="{% url "enrollment:manage" %}"><i class="material-icons">dashboard</i></a></li>
		<li><a class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Home" href="{% url "enrollment:home" %}"><i class="material-icons">picture_in_picture</i></a></li>
      </ul>
    </div>
    {% block content %}
    {% endblock content %}
  </body>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'saisX/js/materialize.js' %}"></script>
  <script src="{% static 'saisX/js/init.js' %}"></script>
  {% block script%}
  {% endblock script%}
</html>